Create Briz Mutation Complete
GraphQLError: Unknown argument \input\  fixed
-> when sending mutation, need to use the same argument name as what is used in resolver